{% set version = "1.14.0" %}

package:
  name: qpoint
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/q/qpoint/qpoint-{{ version }}.tar.gz
  sha256: 6b1714596e1982337acc1c80812b06b9467fb80e7442b6775cddee4318364e99

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61
    - extension-helpers >=1.1.1
    - setuptools-scm >7.0
    - pip
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - python
    - numpy >1.10.0
    - scipy
    - astropy-base
    - _openmp_mutex  # [linux]

test:
  imports:
    - qpoint
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/qpoint/
  summary: A lightweight quaternion-based library for efficient telescope pointing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iparask
    - arahlin
